es1:
  image: baselibrary/elasticsearch:1.7
  net: host
  command: "--cluster.name=unicast \
            --network.publish_host=192.168.99.100 \
            --http.port=19200 \
            --transport.tcp.port=19300 \
            --discovery.zen.ping.multicast.enabled=false \
            --discovery.zen.ping.unicast.hosts=192.168.99.100:19300,192.168.99.100:19302,192.168.99.100:19304 \
           "
es2:
  image: baselibrary/elasticsearch:1.7
  net: host
  command: "--cluster.name=unicast \
            --network.publish_host=192.168.99.100 \
            --http.port=19202 \
            --transport.tcp.port=19302 \
            --discovery.zen.ping.multicast.enabled=false \
            --discovery.zen.ping.unicast.hosts=192.168.99.100:19300,192.168.99.100:19302,192.168.99.100:19304 \
           "
es3:
  image: baselibrary/elasticsearch:1.7
  net: host
  command: "--cluster.name=unicast \
            --network.publish_host=192.168.99.100 \
            --http.port=19204 \
            --transport.tcp.port=19304 \
            --discovery.zen.ping.multicast.enabled=false \
            --discovery.zen.ping.unicast.hosts=192.168.99.100:19300,192.168.99.100:19302,192.168.99.100:19304 \
           "
