es1:
  image: baselibrary/elasticsearch:1.7
  net: host
  command: "--cluster.name=unicast \
            --network.publish_host=192.168.99.100 \
            --http.publish_port=9200 \
            --transport.tcp.publish_port=9300 \
            --discovery.zen.ping.multicast.enabled=false \
            --discovery.zen.ping.unicast.hosts=192.168.99.100:9300,192.168.99.100:9304,192.168.99.100:9304 \
           "
es2:
  image: baselibrary/elasticsearch:1.7
  net: host
  command: "--cluster.name=unicast \
            --network.publish_host=192.168.99.100 \
            --http.publish_port=9202 \
            --transport.tcp.publish_port=9302 \
            --discovery.zen.ping.multicast.enabled=false \
            --discovery.zen.ping.unicast.hosts=192.168.99.100:9300,192.168.99.100:9304,192.168.99.100:9304 \
           "
es3:
  image: baselibrary/elasticsearch:1.7
  net: host
  command: "--cluster.name=unicast \
            --network.publish_host=192.168.99.100 \
            --http.publish_port=9204 \
            --transport.tcp.publish_port=9304 \
            --discovery.zen.ping.multicast.enabled=false \
            --discovery.zen.ping.unicast.hosts=192.168.99.100:9300,192.168.99.100:9304,192.168.99.100:9304 \
           "
